// Web checkout is generated per account by the existing app; never link to another user's invoice.
export const CHECKOUT_URL = 'https://panzerirun.eltonpanzeripersonal.com.br';
export const WEB_PRICE = 'R$ 19,90';
export const results = [
  [
    21,
    746,
    1280,
    'Primeiros 5 km',
    'Eu já estava prestes a desistir da corrida.',
    'Ela achava que corrida talvez não fosse para ela. Depois vieram os primeiros 5 km direto, sem parar.',
  ],
  [
    4,
    899,
    1280,
    'Primeiros 5 km',
    'Nunca achei que conseguiria fazer 5 km.',
    'Uma conquista objetiva que mudou a percepção sobre aquilo que ela acreditava ser capaz de fazer.',
  ],
  [
    11,
    759,
    1280,
    '10 km',
    'Seguindo fielmente todos os treinos, fiz meus primeiros 10 km depois de 8 anos.',
    'O treinamento precisa construir capacidade ao longo do tempo.',
  ],
  [
    9,
    819,
    1280,
    '10 km',
    'Destravei os 10 km.',
    'No relato dela, o resultado envolveu corpo e cabeça. Por isso o processo inteiro importa.',
  ],
  [
    1,
    1114,
    1280,
    'Evolução',
    'Consigo enxergar de verdade a minha evolução.',
    'Desafios progressivos transformam treino em evidência concreta de capacidade.',
  ],
  [
    8,
    832,
    1280,
    'Performance',
    'Bati meu RP!',
    'O método também precisa funcionar para quem já corre e quer evoluir o desempenho.',
  ],
  [
    2,
    1078,
    1280,
    'Confiança',
    'Há um ano, nem imaginava que isso seria possível.',
    'Uma conquista construída ao longo do processo.',
  ],
  [
    3,
    1170,
    613,
    'Consistência',
    'Estou muito realizado com a corrida.',
    'O significado do treinamento também aparece fora dos números.',
  ],
  [
    5,
    1170,
    897,
    'Primeiros 5 km',
    'Depois que você me fez correr 5 km…',
    'A primeira conquista abre espaço para novos objetivos.',
  ],
  [
    6,
    1170,
    970,
    'Distância',
    'Nunca achei que iria aguentar correr assim.',
    'O corredor percebe na prática a capacidade que vem construindo.',
  ],
  [
    7,
    677,
    1280,
    'Performance',
    'Um recorde pessoal nos 10 km.',
    'Um relato sobre esforço, confiança e a experiência da prova.',
  ],
  [
    10,
    721,
    1280,
    'Consistência',
    'Apoio e preparo que fazem diferença.',
    'Registro real de uma sessão de corrida.',
  ],
  [
    12,
    780,
    1280,
    'Confiança',
    'Superar o desconforto e ser forte no final.',
    'A experiência da corrida também transforma a percepção de capacidade.',
  ],
  [
    13,
    735,
    1280,
    'Distância',
    'Um novo RP em 10 milhas.',
    'A conquista aparece no registro da atividade e na mensagem espontânea.',
  ],
  [
    14,
    1170,
    1044,
    'Confiança',
    'Pode ter certeza que falo com muita admiração.',
    'Relato espontâneo sobre a experiência com o treinamento.',
  ],
  [
    15,
    1169,
    643,
    'Novos objetivos',
    'Ainda me prepara para cada novo desafio.',
    'Mais capacidade para continuar construindo o caminho.',
  ],
  [
    16,
    719,
    1280,
    'Novos objetivos',
    'Vamos com calma.',
    'Objetivo, intensidade e progressão precisam caminhar juntos.',
  ],
  [
    17,
    735,
    1280,
    'Consistência',
    'Mais disposição para superar.',
    'A prática de exercício também faz parte da vida real.',
  ],
  [
    18,
    1009,
    1280,
    'Primeiros 5 km',
    'Estou começando a achar os 5 km fáceis.',
    'Uma distância que passa a ser percebida de outra maneira.',
  ],
  [
    19,
    753,
    1280,
    'Confiança',
    'O final foi incrível!',
    'Uma conquista que ganha significado para quem correu.',
  ],
  [
    20,
    729,
    1280,
    'Primeiros 5 km',
    'Meus primeiros 5 km correndo sem parar.',
    'O primeiro marco de um novo caminho.',
  ],
].map(([source, width, height, category, title, description], index) => ({
  id: `result-${String(source).padStart(2, '0')}`,
  source: Number(source),
  width: Number(width),
  height: Number(height),
  category: String(category),
  title: String(title),
  description: String(description),
  featured: index < 6,
  image: `/landing-assets/result-${String(source).padStart(2, '0')}.jpeg`,
}));
export const faq = [
  [
    'Sou completamente iniciante. Posso usar?',
    'Sim. O ponto de partida considera aquilo que você consegue fazer hoje. O planejamento progride a partir da sua capacidade atual.',
  ],
  [
    'Já corro. O Panzeri Run também serve para mim?',
    'Sim. O planejamento também atende corredores que já treinam e querem melhorar distância, consistência ou desempenho.',
  ],
  [
    'Serve para 5 km, 10 km, meia e maratona?',
    'Sim. A avaliação inicial contempla objetivos de 5 km, 10 km, meia maratona e maratona, respeitando seu nível atual.',
  ],
  [
    'O Panzeri Run usa inteligência artificial?',
    'Sim. Usamos inteligência artificial para reunir e cruzar informações sobre seu histórico, rotina, treinos realizados e respostas ao esforço, ampliando a profundidade da personalização. Sua atuação é orientada por critérios e instruções desenvolvidos pessoalmente por Elton Panzeri, treinador desde 2009, a partir das ciências do esporte, do comportamento e da mente. A tecnologia amplia a capacidade de análise; torna a prescrição ainda mais profunda e assertiva.',
  ],
  [
    'O que acontece se eu perder um treino?',
    'Registre a sessão como não realizada e informe o contexto no check-in semanal. Essas informações participam da reavaliação do planejamento. Um registro isolado não significa que todo o plano será alterado imediatamente.',
  ],
  [
    'Tem treino de força?',
    'Sim, quando aplicável ao planejamento e dentro das funcionalidades atualmente disponíveis.',
  ],
  [
    'Preciso de Garmin ou outro relógio?',
    'Não. Você não precisa de um relógio esportivo. O aplicativo coleta, por meio da avaliação, dos registros de treino e dos questionários, as informações necessárias para personalizar seu treinamento.',
  ],
  [
    'E se eu sentir dor?',
    'Pensamos nisso também. O Panzeri Run conta com diferentes questionários para investigar em profundidade os relatos de dor e o histórico de lesões: onde incomoda, quando começou, em quais situações aparece e como interfere no treinamento. Essas informações ajudam a orientar ajustes específicos e a reconhecer situações que precisam de atenção profissional. Casos que exigem revisão individual podem ser encaminhados para a intervenção de Elton, inclusive para orientar a busca de atendimento presencial. O aplicativo não faz diagnóstico nem substitui avaliação médica ou fisioterapêutica, e não é um serviço de urgência.',
  ],
  [
    'É uma consultoria individual diretamente com Elton?',
    'A assinatura do aplicativo utiliza o método e os critérios desenvolvidos por Elton, mas não equivale a uma consultoria individual diretamente com ele. Para quem deseja esse acompanhamento, Elton também oferece mentoria individualizada para corredores. Entre em contato diretamente com ele para conhecer o serviço e receber mais informações.',
  ],
];
