@echo on
setlocal
title Atualizar Panzeri Run no GitHub Desktop

set "ORIGEM=%~dp0"
set "DESTINO=%USERPROFILE%\OneDrive\Documentos\GitHub\panzeri-run-api"

if not exist "%DESTINO%\apps\api" (
  echo Nao encontrei a pasta do projeto no GitHub Desktop.
  echo Esperado: %DESTINO%
  echo Pressione uma tecla para fechar.
  pause >nul
  exit /b 1
)

copy /Y "%ORIGEM%package.json" "%DESTINO%\package.json"
copy /Y "%ORIGEM%pnpm-lock.yaml" "%DESTINO%\pnpm-lock.yaml"
copy /Y "%ORIGEM%pnpm-workspace.yaml" "%DESTINO%\pnpm-workspace.yaml"
copy /Y "%ORIGEM%apps\admin\tsconfig.json" "%DESTINO%\apps\admin\tsconfig.json"
copy /Y "%ORIGEM%Dockerfile" "%DESTINO%\Dockerfile"
copy /Y "%ORIGEM%docker-compose.yml" "%DESTINO%\docker-compose.yml"
copy /Y "%ORIGEM%.env.example" "%DESTINO%\.env.example"
copy /Y "%ORIGEM%.npmrc" "%DESTINO%\.npmrc"
copy /Y "%ORIGEM%PRONTUARIO.md" "%DESTINO%\PRONTUARIO.md"
copy /Y "%ORIGEM%CLAUDE.md" "%DESTINO%\CLAUDE.md"
copy /Y "%ORIGEM%LICOES_COLABORACAO.md" "%DESTINO%\LICOES_COLABORACAO.md"
xcopy /E /I /Y "%ORIGEM%identidade-visual-panzeri-run" "%DESTINO%\identidade-visual-panzeri-run" 1>nul
copy /Y "%ORIGEM%prompt-identidade-visual-chatgpt.md" "%DESTINO%\prompt-identidade-visual-chatgpt.md"
copy /Y "%ORIGEM%DEPLOY_APP_ALUNO.md" "%DESTINO%\DEPLOY_APP_ALUNO.md"
copy /Y "%ORIGEM%PROPOSTA_HARNESS_AGENTES.md" "%DESTINO%\PROPOSTA_HARNESS_AGENTES.md"
copy /Y "%ORIGEM%README.md" "%DESTINO%\README.md"
copy /Y "%ORIGEM%EASY_PANEL.md" "%DESTINO%\EASY_PANEL.md"
copy /Y "%ORIGEM%apps\api\package.json" "%DESTINO%\apps\api\package.json"
copy /Y "%ORIGEM%apps\api\pnpm-lock.yaml" "%DESTINO%\apps\api\pnpm-lock.yaml"
copy /Y "%ORIGEM%apps\api\pnpm-workspace.yaml" "%DESTINO%\apps\api\pnpm-workspace.yaml"
copy /Y "%ORIGEM%apps\api\nest-cli.json" "%DESTINO%\apps\api\nest-cli.json"
copy /Y "%ORIGEM%apps\api\src\billing\dto\apply-coupon.dto.ts" "%DESTINO%\apps\api\src\billing\dto\apply-coupon.dto.ts"
copy /Y "%ORIGEM%apps\api\test\exercise-libraries.spec.ts" "%DESTINO%\apps\api\test\exercise-libraries.spec.ts"
copy /Y "%ORIGEM%apps\api\test\training-methodology.spec.ts" "%DESTINO%\apps\api\test\training-methodology.spec.ts"
copy /Y "%ORIGEM%apps\api\test\auth.service.spec.ts" "%DESTINO%\apps\api\test\auth.service.spec.ts"
copy /Y "%ORIGEM%apps\api\src\coach\coach.controller.ts" "%DESTINO%\apps\api\src\coach\coach.controller.ts"
copy /Y "%ORIGEM%apps\api\src\app.controller.ts" "%DESTINO%\apps\api\src\app.controller.ts"
copy /Y "%ORIGEM%apps\api\src\landing-page.ts" "%DESTINO%\apps\api\src\landing-page.ts"
copy /Y "%ORIGEM%apps\api\tsconfig.json" "%DESTINO%\apps\api\tsconfig.json"
copy /Y "%ORIGEM%apps\api\tsconfig.build.json" "%DESTINO%\apps\api\tsconfig.build.json"
copy /Y "%ORIGEM%apps\api\prisma\schema.prisma" "%DESTINO%\apps\api\prisma\schema.prisma"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260703170000_add_subscription_status" mkdir "%DESTINO%\apps\api\prisma\migrations\20260703170000_add_subscription_status"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260703170000_add_subscription_status\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260703170000_add_subscription_status\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260705120000_add_onboarding_interview" mkdir "%DESTINO%\apps\api\prisma\migrations\20260705120000_add_onboarding_interview"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260705120000_add_onboarding_interview\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260705120000_add_onboarding_interview\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260706120000_repair_empty_onboarding" mkdir "%DESTINO%\apps\api\prisma\migrations\20260706120000_repair_empty_onboarding"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260706120000_repair_empty_onboarding\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260706120000_repair_empty_onboarding\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260708120000_add_exercise_responsibility" mkdir "%DESTINO%\apps\api\prisma\migrations\20260708120000_add_exercise_responsibility"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260708120000_add_exercise_responsibility\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260708120000_add_exercise_responsibility\migration.sql"
copy /Y "%ORIGEM%apps\api\src\auth\auth.service.ts" "%DESTINO%\apps\api\src\auth\auth.service.ts"
copy /Y "%ORIGEM%apps\api\src\auth\auth.controller.ts" "%DESTINO%\apps\api\src\auth\auth.controller.ts"
copy /Y "%ORIGEM%apps\api\src\auth\dto\register.dto.ts" "%DESTINO%\apps\api\src\auth\dto\register.dto.ts"
copy /Y "%ORIGEM%apps\api\src\me\me.controller.ts" "%DESTINO%\apps\api\src\me\me.controller.ts"
copy /Y "%ORIGEM%apps\api\src\me\me.service.ts" "%DESTINO%\apps\api\src\me\me.service.ts"
copy /Y "%ORIGEM%apps\api\src\me\me.module.ts" "%DESTINO%\apps\api\src\me\me.module.ts"
copy /Y "%ORIGEM%apps\api\src\coach\coach.service.ts" "%DESTINO%\apps\api\src\coach\coach.service.ts"
copy /Y "%ORIGEM%apps\api\src\coach\coach.module.ts" "%DESTINO%\apps\api\src\coach\coach.module.ts"
copy /Y "%ORIGEM%apps\api\src\coach\coach-tooling.controller.ts" "%DESTINO%\apps\api\src\coach\coach-tooling.controller.ts"
copy /Y "%ORIGEM%apps\api\src\coach\dashboard-query.util.ts" "%DESTINO%\apps\api\src\coach\dashboard-query.util.ts"
copy /Y "%ORIGEM%apps\api\src\common\claude-tooling.guard.ts" "%DESTINO%\apps\api\src\common\claude-tooling.guard.ts"
copy /Y "%ORIGEM%apps\api\src\coach\dto\update-training-session.dto.ts" "%DESTINO%\apps\api\src\coach\dto\update-training-session.dto.ts"
copy /Y "%ORIGEM%apps\api\src\coach\dto\update-student.dto.ts" "%DESTINO%\apps\api\src\coach\dto\update-student.dto.ts"
copy /Y "%ORIGEM%apps\api\src\coach\dto\merge-student.dto.ts" "%DESTINO%\apps\api\src\coach\dto\merge-student.dto.ts"
copy /Y "%ORIGEM%apps\api\src\notifications\notifications.service.ts" "%DESTINO%\apps\api\src\notifications\notifications.service.ts"
copy /Y "%ORIGEM%apps\api\src\notifications\notifications.controller.ts" "%DESTINO%\apps\api\src\notifications\notifications.controller.ts"
copy /Y "%ORIGEM%apps\api\src\notifications\notifications.module.ts" "%DESTINO%\apps\api\src\notifications\notifications.module.ts"
copy /Y "%ORIGEM%apps\api\src\notifications\push-notification.service.ts" "%DESTINO%\apps\api\src\notifications\push-notification.service.ts"
if not exist "%DESTINO%\apps\api\src\notifications\dto" mkdir "%DESTINO%\apps\api\src\notifications\dto"
copy /Y "%ORIGEM%apps\api\src\notifications\dto\register-push-token.dto.ts" "%DESTINO%\apps\api\src\notifications\dto\register-push-token.dto.ts"
copy /Y "%ORIGEM%apps\api\src\workout-completions\workout-completions.controller.ts" "%DESTINO%\apps\api\src\workout-completions\workout-completions.controller.ts"
copy /Y "%ORIGEM%apps\api\src\workout-completions\workout-completions.service.ts" "%DESTINO%\apps\api\src\workout-completions\workout-completions.service.ts"
copy /Y "%ORIGEM%apps\api\src\workout-completions\dto\upsert-workout-completion.dto.ts" "%DESTINO%\apps\api\src\workout-completions\dto\upsert-workout-completion.dto.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\training-plans.service.ts" "%DESTINO%\apps\api\src\training-plans\training-plans.service.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\training-plans.controller.ts" "%DESTINO%\apps\api\src\training-plans\training-plans.controller.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\training-methodology.ts" "%DESTINO%\apps\api\src\training-plans\training-methodology.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\prescription-agent.service.ts" "%DESTINO%\apps\api\src\training-plans\prescription-agent.service.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\panzeri-methodology-knowledge.ts" "%DESTINO%\apps\api\src\training-plans\panzeri-methodology-knowledge.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\gym-exercise-library.ts" "%DESTINO%\apps\api\src\training-plans\gym-exercise-library.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\runner-strength-library.ts" "%DESTINO%\apps\api\src\training-plans\runner-strength-library.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\training-plans.module.ts" "%DESTINO%\apps\api\src\training-plans\training-plans.module.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\weekly-checkin.service.ts" "%DESTINO%\apps\api\src\training-plans\weekly-checkin.service.ts"
if not exist "%DESTINO%\apps\api\src\training-plans\dto" mkdir "%DESTINO%\apps\api\src\training-plans\dto"
copy /Y "%ORIGEM%apps\api\src\training-plans\dto\submit-weekly-checkin.dto.ts" "%DESTINO%\apps\api\src\training-plans\dto\submit-weekly-checkin.dto.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260831120000_add_weekly_checkin" mkdir "%DESTINO%\apps\api\prisma\migrations\20260831120000_add_weekly_checkin"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260831120000_add_weekly_checkin\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260831120000_add_weekly_checkin\migration.sql"
copy /Y "%ORIGEM%apps\api\src\training-plans\weekly-plan-scheduler.service.ts" "%DESTINO%\apps\api\src\training-plans\weekly-plan-scheduler.service.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\strava-analysis-scheduler.service.ts" "%DESTINO%\apps\api\src\training-plans\strava-analysis-scheduler.service.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\directive-expiry-notifier.service.ts" "%DESTINO%\apps\api\src\training-plans\directive-expiry-notifier.service.ts"
if not exist "%DESTINO%\apps\api\src\observations\dto" mkdir "%DESTINO%\apps\api\src\observations\dto"
copy /Y "%ORIGEM%apps\api\src\observations\observations.controller.ts" "%DESTINO%\apps\api\src\observations\observations.controller.ts"
copy /Y "%ORIGEM%apps\api\src\observations\observations.service.ts" "%DESTINO%\apps\api\src\observations\observations.service.ts"
copy /Y "%ORIGEM%apps\api\src\observations\observations.module.ts" "%DESTINO%\apps\api\src\observations\observations.module.ts"
copy /Y "%ORIGEM%apps\api\src\observations\dto\create-observation.dto.ts" "%DESTINO%\apps\api\src\observations\dto\create-observation.dto.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260726090000_add_plan_explanation_and_observations" mkdir "%DESTINO%\apps\api\prisma\migrations\20260726090000_add_plan_explanation_and_observations"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260726090000_add_plan_explanation_and_observations\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260726090000_add_plan_explanation_and_observations\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260728020000_drop_plan_explanation" mkdir "%DESTINO%\apps\api\prisma\migrations\20260728020000_drop_plan_explanation"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260728020000_drop_plan_explanation\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260728020000_drop_plan_explanation\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260728030000_workout_completion_duration_float" mkdir "%DESTINO%\apps\api\prisma\migrations\20260728030000_workout_completion_duration_float"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260728030000_workout_completion_duration_float\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260728030000_workout_completion_duration_float\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260728040000_add_last_routine_change_at" mkdir "%DESTINO%\apps\api\prisma\migrations\20260728040000_add_last_routine_change_at"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260728040000_add_last_routine_change_at\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260728040000_add_last_routine_change_at\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260729160000_add_strava_analysis_cache" mkdir "%DESTINO%\apps\api\prisma\migrations\20260729160000_add_strava_analysis_cache"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260729160000_add_strava_analysis_cache\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260729160000_add_strava_analysis_cache\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260729180000_alter_strava_analysis_cache_nullable" mkdir "%DESTINO%\apps\api\prisma\migrations\20260729180000_alter_strava_analysis_cache_nullable"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260729180000_alter_strava_analysis_cache_nullable\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260729180000_alter_strava_analysis_cache_nullable\migration.sql"
copy /Y "%ORIGEM%apps\api\src\strava\strava.controller.ts" "%DESTINO%\apps\api\src\strava\strava.controller.ts"
copy /Y "%ORIGEM%apps\api\src\strava\strava.service.ts" "%DESTINO%\apps\api\src\strava\strava.service.ts"
copy /Y "%ORIGEM%apps\api\src\strava\strava.module.ts" "%DESTINO%\apps\api\src\strava\strava.module.ts"
copy /Y "%ORIGEM%apps\admin\app\page.tsx" "%DESTINO%\apps\admin\app\page.tsx"
copy /Y "%ORIGEM%apps\admin\app\styles.css" "%DESTINO%\apps\admin\app\styles.css"
copy /Y "%ORIGEM%apps\mobile\App.tsx" "%DESTINO%\apps\mobile\App.tsx"
copy /Y "%ORIGEM%apps\mobile\public\sw.js" "%DESTINO%\apps\mobile\public\sw.js"
copy /Y "%ORIGEM%apps\mobile\public\icon.svg" "%DESTINO%\apps\mobile\public\icon.svg"
copy /Y "%ORIGEM%apps\mobile\public\manifest.json" "%DESTINO%\apps\mobile\public\manifest.json"
copy /Y "%ORIGEM%apps\mobile\nginx.conf" "%DESTINO%\apps\mobile\nginx.conf"
copy /Y "%ORIGEM%apps\mobile\package.json" "%DESTINO%\apps\mobile\package.json"
copy /Y "%ORIGEM%apps\mobile\app.json" "%DESTINO%\apps\mobile\app.json"
copy /Y "%ORIGEM%apps\mobile\eas.json" "%DESTINO%\apps\mobile\eas.json"
if not exist "%DESTINO%\apps\mobile\theme" mkdir "%DESTINO%\apps\mobile\theme"
copy /Y "%ORIGEM%apps\mobile\theme\tokens.ts" "%DESTINO%\apps\mobile\theme\tokens.ts"
copy /Y "%ORIGEM%apps\mobile\theme\BrandMark.tsx" "%DESTINO%\apps\mobile\theme\BrandMark.tsx"
if not exist "%DESTINO%\apps\mobile\assets\brand" mkdir "%DESTINO%\apps\mobile\assets\brand"
copy /Y "%ORIGEM%apps\mobile\assets\brand\icon-ios.png" "%DESTINO%\apps\mobile\assets\brand\icon-ios.png"
copy /Y "%ORIGEM%apps\mobile\assets\brand\adaptive-icon-foreground.png" "%DESTINO%\apps\mobile\assets\brand\adaptive-icon-foreground.png"
copy /Y "%ORIGEM%apps\mobile\assets\brand\splash.png" "%DESTINO%\apps\mobile\assets\brand\splash.png"
copy /Y "%ORIGEM%apps\mobile\assets\brand\favicon.png" "%DESTINO%\apps\mobile\assets\brand\favicon.png"
copy /Y "%ORIGEM%apps\mobile\assets\brand\symbol-primary.svg" "%DESTINO%\apps\mobile\assets\brand\symbol-primary.svg"

copy /Y "%ORIGEM%apps\api\src\app.module.ts" "%DESTINO%\apps\api\src\app.module.ts"
copy /Y "%ORIGEM%apps\api\src\main.ts" "%DESTINO%\apps\api\src\main.ts"
if not exist "%DESTINO%\apps\api\src\billing\dto" mkdir "%DESTINO%\apps\api\src\billing\dto"
copy /Y "%ORIGEM%apps\api\src\billing\billing.controller.ts" "%DESTINO%\apps\api\src\billing\billing.controller.ts"
copy /Y "%ORIGEM%apps\api\src\billing\billing.module.ts" "%DESTINO%\apps\api\src\billing\billing.module.ts"
copy /Y "%ORIGEM%apps\api\src\billing\billing.service.ts" "%DESTINO%\apps\api\src\billing\billing.service.ts"
copy /Y "%ORIGEM%apps\api\src\billing\billing-sync-scheduler.service.ts" "%DESTINO%\apps\api\src\billing\billing-sync-scheduler.service.ts"
copy /Y "%ORIGEM%apps\api\src\billing\telegram.service.ts" "%DESTINO%\apps\api\src\billing\telegram.service.ts"
copy /Y "%ORIGEM%apps\api\src\billing\dto\create-checkout.dto.ts" "%DESTINO%\apps\api\src\billing\dto\create-checkout.dto.ts"
del /F /Q "%DESTINO%\apps\api\src\billing\dto\efi-notification.dto.ts" 2>nul
if not exist "%DESTINO%\apps\api\prisma\migrations\20260708180000_add_efi_billing" mkdir "%DESTINO%\apps\api\prisma\migrations\20260708180000_add_efi_billing"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260708180000_add_efi_billing\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260708180000_add_efi_billing\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260714120000_add_asaas_billing" mkdir "%DESTINO%\apps\api\prisma\migrations\20260714120000_add_asaas_billing"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260714120000_add_asaas_billing\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260714120000_add_asaas_billing\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260715120000_add_completion_satisfaction" mkdir "%DESTINO%\apps\api\prisma\migrations\20260715120000_add_completion_satisfaction"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260715120000_add_completion_satisfaction\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260715120000_add_completion_satisfaction\migration.sql"

if not exist "%DESTINO%\apps\api\prisma\migrations\20260717120000_add_phone_and_message_log" mkdir "%DESTINO%\apps\api\prisma\migrations\20260717120000_add_phone_and_message_log"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260717120000_add_phone_and_message_log\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260717120000_add_phone_and_message_log\migration.sql"
if not exist "%DESTINO%\apps\api\src\messaging" mkdir "%DESTINO%\apps\api\src\messaging"
copy /Y "%ORIGEM%apps\api\src\messaging\email.service.ts" "%DESTINO%\apps\api\src\messaging\email.service.ts"
copy /Y "%ORIGEM%apps\api\src\messaging\messaging.service.ts" "%DESTINO%\apps\api\src\messaging\messaging.service.ts"
copy /Y "%ORIGEM%apps\api\src\messaging\messaging.module.ts" "%DESTINO%\apps\api\src\messaging\messaging.module.ts"
copy /Y "%ORIGEM%apps\api\src\messaging\messaging.controller.ts" "%DESTINO%\apps\api\src\messaging\messaging.controller.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260827145000_add_message_log_delivery_tracking" mkdir "%DESTINO%\apps\api\prisma\migrations\20260827145000_add_message_log_delivery_tracking"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260827145000_add_message_log_delivery_tracking\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260827145000_add_message_log_delivery_tracking\migration.sql"
copy /Y "%ORIGEM%apps\api\src\messaging\notification-triggers.service.ts" "%DESTINO%\apps\api\src\messaging\notification-triggers.service.ts"
copy /Y "%ORIGEM%apps\api\src\messaging\prospect-level.ts" "%DESTINO%\apps\api\src\messaging\prospect-level.ts"
copy /Y "%ORIGEM%apps\api\src\messaging\prospect-nurture.service.ts" "%DESTINO%\apps\api\src\messaging\prospect-nurture.service.ts"
copy /Y "%ORIGEM%apps\api\src\coach\dto\send-student-message.dto.ts" "%DESTINO%\apps\api\src\coach\dto\send-student-message.dto.ts"
copy /Y "%ORIGEM%apps\api\src\fitness-tests\fitness-tests.service.ts" "%DESTINO%\apps\api\src\fitness-tests\fitness-tests.service.ts"
copy /Y "%ORIGEM%apps\api\src\fitness-tests\fitness-tests.controller.ts" "%DESTINO%\apps\api\src\fitness-tests\fitness-tests.controller.ts"

if not exist "%DESTINO%\apps\api\prisma\migrations\20260720120000_add_strava_cadence" mkdir "%DESTINO%\apps\api\prisma\migrations\20260720120000_add_strava_cadence"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260720120000_add_strava_cadence\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260720120000_add_strava_cadence\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260720130000_add_reassessment" mkdir "%DESTINO%\apps\api\prisma\migrations\20260720130000_add_reassessment"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260720130000_add_reassessment\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260720130000_add_reassessment\migration.sql"
copy /Y "%ORIGEM%apps\api\src\training-plans\strava-analysis-agent.service.ts" "%DESTINO%\apps\api\src\training-plans\strava-analysis-agent.service.ts"
if not exist "%DESTINO%\apps\api\src\reassessment" mkdir "%DESTINO%\apps\api\src\reassessment"
copy /Y "%ORIGEM%apps\api\src\reassessment\reassessment.service.ts" "%DESTINO%\apps\api\src\reassessment\reassessment.service.ts"
copy /Y "%ORIGEM%apps\api\src\reassessment\reassessment.controller.ts" "%DESTINO%\apps\api\src\reassessment\reassessment.controller.ts"
copy /Y "%ORIGEM%apps\api\src\reassessment\reassessment.module.ts" "%DESTINO%\apps\api\src\reassessment\reassessment.module.ts"
copy /Y "%ORIGEM%apps\api\src\reassessment\evolution-agent.service.ts" "%DESTINO%\apps\api\src\reassessment\evolution-agent.service.ts"

if not exist "%DESTINO%\apps\api\src\common" mkdir "%DESTINO%\apps\api\src\common"
copy /Y "%ORIGEM%apps\api\src\common\ai-queue.service.ts" "%DESTINO%\apps\api\src\common\ai-queue.service.ts"
copy /Y "%ORIGEM%apps\api\src\common\ai-queue.module.ts" "%DESTINO%\apps\api\src\common\ai-queue.module.ts"

if not exist "%DESTINO%\apps\api\src\backup" mkdir "%DESTINO%\apps\api\src\backup"
copy /Y "%ORIGEM%apps\api\src\backup\backup.service.ts" "%DESTINO%\apps\api\src\backup\backup.service.ts"
copy /Y "%ORIGEM%apps\api\src\backup\backup.module.ts" "%DESTINO%\apps\api\src\backup\backup.module.ts"

if not exist "%DESTINO%\apps\api\prisma\migrations\20260721120000_add_technical_manager_agent" mkdir "%DESTINO%\apps\api\prisma\migrations\20260721120000_add_technical_manager_agent"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260721120000_add_technical_manager_agent\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260721120000_add_technical_manager_agent\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260722140000_add_user_education" mkdir "%DESTINO%\apps\api\prisma\migrations\20260722140000_add_user_education"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260722140000_add_user_education\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260722140000_add_user_education\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260722150000_add_target_race_pain_report" mkdir "%DESTINO%\apps\api\prisma\migrations\20260722150000_add_target_race_pain_report"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260722150000_add_target_race_pain_report\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260722150000_add_target_race_pain_report\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260722160000_add_directive_expiry" mkdir "%DESTINO%\apps\api\prisma\migrations\20260722160000_add_directive_expiry"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260722160000_add_directive_expiry\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260722160000_add_directive_expiry\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260724090000_add_subscription_manual_override" mkdir "%DESTINO%\apps\api\prisma\migrations\20260724090000_add_subscription_manual_override"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260724090000_add_subscription_manual_override\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260724090000_add_subscription_manual_override\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260725010000_add_session_recommendations" mkdir "%DESTINO%\apps\api\prisma\migrations\20260725010000_add_session_recommendations"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260725010000_add_session_recommendations\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260725010000_add_session_recommendations\migration.sql"
if not exist "%DESTINO%\apps\api\src\technical-manager\dto" mkdir "%DESTINO%\apps\api\src\technical-manager\dto"
copy /Y "%ORIGEM%apps\api\src\technical-manager\technical-manager-agent.service.ts" "%DESTINO%\apps\api\src\technical-manager\technical-manager-agent.service.ts"
copy /Y "%ORIGEM%apps\api\src\technical-manager\technical-manager.controller.ts" "%DESTINO%\apps\api\src\technical-manager\technical-manager.controller.ts"
copy /Y "%ORIGEM%apps\api\src\technical-manager\technical-manager.module.ts" "%DESTINO%\apps\api\src\technical-manager\technical-manager.module.ts"
copy /Y "%ORIGEM%apps\api\src\technical-manager\dto\send-chat-message.dto.ts" "%DESTINO%\apps\api\src\technical-manager\dto\send-chat-message.dto.ts"
if not exist "%DESTINO%\apps\api\src\target-races\dto" mkdir "%DESTINO%\apps\api\src\target-races\dto"
copy /Y "%ORIGEM%apps\api\src\target-races\target-races.controller.ts" "%DESTINO%\apps\api\src\target-races\target-races.controller.ts"
copy /Y "%ORIGEM%apps\api\src\target-races\target-races.service.ts" "%DESTINO%\apps\api\src\target-races\target-races.service.ts"
copy /Y "%ORIGEM%apps\api\src\target-races\target-races.module.ts" "%DESTINO%\apps\api\src\target-races\target-races.module.ts"
copy /Y "%ORIGEM%apps\api\src\target-races\dto\create-target-race.dto.ts" "%DESTINO%\apps\api\src\target-races\dto\create-target-race.dto.ts"
copy /Y "%ORIGEM%apps\api\src\target-races\dto\update-target-race.dto.ts" "%DESTINO%\apps\api\src\target-races\dto\update-target-race.dto.ts"
if not exist "%DESTINO%\apps\api\src\pain-reports\dto" mkdir "%DESTINO%\apps\api\src\pain-reports\dto"
copy /Y "%ORIGEM%apps\api\src\pain-reports\pain-reports.controller.ts" "%DESTINO%\apps\api\src\pain-reports\pain-reports.controller.ts"
copy /Y "%ORIGEM%apps\api\src\pain-reports\pain-reports.service.ts" "%DESTINO%\apps\api\src\pain-reports\pain-reports.service.ts"
copy /Y "%ORIGEM%apps\api\src\pain-reports\pain-reports.module.ts" "%DESTINO%\apps\api\src\pain-reports\pain-reports.module.ts"
copy /Y "%ORIGEM%apps\api\src\pain-reports\dto\create-pain-report.dto.ts" "%DESTINO%\apps\api\src\pain-reports\dto\create-pain-report.dto.ts"

copy /Y "%ORIGEM%apps\api\src\training-plans\student-profile.service.ts" "%DESTINO%\apps\api\src\training-plans\student-profile.service.ts"
copy /Y "%ORIGEM%apps\api\src\training-plans\student-profile.module.ts" "%DESTINO%\apps\api\src\training-plans\student-profile.module.ts"
copy /Y "%ORIGEM%apps\api\src\workout-completions\workout-completions.module.ts" "%DESTINO%\apps\api\src\workout-completions\workout-completions.module.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260730120000_add_student_profile" mkdir "%DESTINO%\apps\api\prisma\migrations\20260730120000_add_student_profile"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260730120000_add_student_profile\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260730120000_add_student_profile\migration.sql"

copy /Y "%ORIGEM%apps\api\src\billing\billing.service.ts" "%DESTINO%\apps\api\src\billing\billing.service.ts"
copy /Y "%ORIGEM%apps\api\src\me\me.module.ts" "%DESTINO%\apps\api\src\me\me.module.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260731100000_add_student_code" mkdir "%DESTINO%\apps\api\prisma\migrations\20260731100000_add_student_code"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260731100000_add_student_code\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260731100000_add_student_code\migration.sql"

copy /Y "%ORIGEM%apps\api\src\coach\dto\create-manual-session.dto.ts" "%DESTINO%\apps\api\src\coach\dto\create-manual-session.dto.ts"

if not exist "%DESTINO%\apps\api\prisma\migrations\20260803180000_add_routine_mismatch_note" mkdir "%DESTINO%\apps\api\prisma\migrations\20260803180000_add_routine_mismatch_note"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260803180000_add_routine_mismatch_note\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260803180000_add_routine_mismatch_note\migration.sql"

if not exist "%DESTINO%\apps\api\prisma\migrations\20260808120000_add_strava_elevation_elapsed" mkdir "%DESTINO%\apps\api\prisma\migrations\20260808120000_add_strava_elevation_elapsed"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260808120000_add_strava_elevation_elapsed\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260808120000_add_strava_elevation_elapsed\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260810120000_add_last_plan_generation_failed_at" mkdir "%DESTINO%\apps\api\prisma\migrations\20260810120000_add_last_plan_generation_failed_at"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260810120000_add_last_plan_generation_failed_at\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260810120000_add_last_plan_generation_failed_at\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260810180000_add_target_race_context_questions" mkdir "%DESTINO%\apps\api\prisma\migrations\20260810180000_add_target_race_context_questions"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260810180000_add_target_race_context_questions\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260810180000_add_target_race_context_questions\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260816120000_add_training_plan_code" mkdir "%DESTINO%\apps\api\prisma\migrations\20260816120000_add_training_plan_code"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260816120000_add_training_plan_code\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260816120000_add_training_plan_code\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260816150000_add_expo_push_token" mkdir "%DESTINO%\apps\api\prisma\migrations\20260816150000_add_expo_push_token"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260816150000_add_expo_push_token\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260816150000_add_expo_push_token\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260816220000_add_generation_attempt_limits" mkdir "%DESTINO%\apps\api\prisma\migrations\20260816220000_add_generation_attempt_limits"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260816220000_add_generation_attempt_limits\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260816220000_add_generation_attempt_limits\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260818130000_defer_student_code" mkdir "%DESTINO%\apps\api\prisma\migrations\20260818130000_defer_student_code"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260818130000_defer_student_code\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260818130000_defer_student_code\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260818140000_add_login_link_token" mkdir "%DESTINO%\apps\api\prisma\migrations\20260818140000_add_login_link_token"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260818140000_add_login_link_token\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260818140000_add_login_link_token\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260818150000_add_quick_intake_completed_at" mkdir "%DESTINO%\apps\api\prisma\migrations\20260818150000_add_quick_intake_completed_at"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260818150000_add_quick_intake_completed_at\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260818150000_add_quick_intake_completed_at\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260818160000_add_pain_report_trend_and_impact" mkdir "%DESTINO%\apps\api\prisma\migrations\20260818160000_add_pain_report_trend_and_impact"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260818160000_add_pain_report_trend_and_impact\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260818160000_add_pain_report_trend_and_impact\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260819170000_add_workout_satisfaction_dimensions" mkdir "%DESTINO%\apps\api\prisma\migrations\20260819170000_add_workout_satisfaction_dimensions"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260819170000_add_workout_satisfaction_dimensions\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260819170000_add_workout_satisfaction_dimensions\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260826160000_add_subscription_provider" mkdir "%DESTINO%\apps\api\prisma\migrations\20260826160000_add_subscription_provider"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260826160000_add_subscription_provider\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260826160000_add_subscription_provider\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260827115000_add_subscription_cancel_requested_at" mkdir "%DESTINO%\apps\api\prisma\migrations\20260827115000_add_subscription_cancel_requested_at"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260827115000_add_subscription_cancel_requested_at\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260827115000_add_subscription_cancel_requested_at\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260904120000_add_free_tester_email" mkdir "%DESTINO%\apps\api\prisma\migrations\20260904120000_add_free_tester_email"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260904120000_add_free_tester_email\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260904120000_add_free_tester_email\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260905100000_billing_notifications_infra" mkdir "%DESTINO%\apps\api\prisma\migrations\20260905100000_billing_notifications_infra"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260905100000_billing_notifications_infra\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260905100000_billing_notifications_infra\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260907200000_add_funnel_events" mkdir "%DESTINO%\apps\api\prisma\migrations\20260907200000_add_funnel_events"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260907200000_add_funnel_events\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260907200000_add_funnel_events\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260909180000_add_training_session_evolution_index" mkdir "%DESTINO%\apps\api\prisma\migrations\20260909180000_add_training_session_evolution_index"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260909180000_add_training_session_evolution_index\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260909180000_add_training_session_evolution_index\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260911120000_add_cancel_survey_fields" mkdir "%DESTINO%\apps\api\prisma\migrations\20260911120000_add_cancel_survey_fields"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260911120000_add_cancel_survey_fields\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260911120000_add_cancel_survey_fields\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260911190000_add_weekly_checkin_v2" mkdir "%DESTINO%\apps\api\prisma\migrations\20260911190000_add_weekly_checkin_v2"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260911190000_add_weekly_checkin_v2\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260911190000_add_weekly_checkin_v2\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260911200000_add_menstrual_cycle" mkdir "%DESTINO%\apps\api\prisma\migrations\20260911200000_add_menstrual_cycle"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260911200000_add_menstrual_cycle\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260911200000_add_menstrual_cycle\migration.sql"
if not exist "%DESTINO%\apps\api\src\menstrual-cycle\dto" mkdir "%DESTINO%\apps\api\src\menstrual-cycle\dto"
copy /Y "%ORIGEM%apps\api\src\menstrual-cycle\menstrual-cycle.service.ts" "%DESTINO%\apps\api\src\menstrual-cycle\menstrual-cycle.service.ts"
copy /Y "%ORIGEM%apps\api\src\menstrual-cycle\menstrual-cycle.controller.ts" "%DESTINO%\apps\api\src\menstrual-cycle\menstrual-cycle.controller.ts"
copy /Y "%ORIGEM%apps\api\src\menstrual-cycle\menstrual-cycle.module.ts" "%DESTINO%\apps\api\src\menstrual-cycle\menstrual-cycle.module.ts"
copy /Y "%ORIGEM%apps\api\src\menstrual-cycle\dto\upsert-menstrual-profile.dto.ts" "%DESTINO%\apps\api\src\menstrual-cycle\dto\upsert-menstrual-profile.dto.ts"
copy /Y "%ORIGEM%apps\api\src\menstrual-cycle\dto\create-cycle-log.dto.ts" "%DESTINO%\apps\api\src\menstrual-cycle\dto\create-cycle-log.dto.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260911210000_add_workout_feedback_v2" mkdir "%DESTINO%\apps\api\prisma\migrations\20260911210000_add_workout_feedback_v2"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260911210000_add_workout_feedback_v2\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260911210000_add_workout_feedback_v2\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260915120000_add_funnel_journey_and_first_paid" mkdir "%DESTINO%\apps\api\prisma\migrations\20260915120000_add_funnel_journey_and_first_paid"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260915120000_add_funnel_journey_and_first_paid\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260915120000_add_funnel_journey_and_first_paid\migration.sql"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260916164659_add_data_layer_phase_0" mkdir "%DESTINO%\apps\api\prisma\migrations\20260916164659_add_data_layer_phase_0"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260916164659_add_data_layer_phase_0\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260916164659_add_data_layer_phase_0\migration.sql"
if not exist "%DESTINO%\apps\api\src\evolution" mkdir "%DESTINO%\apps\api\src\evolution"
copy /Y "%ORIGEM%apps\api\src\evolution\evolution.controller.ts" "%DESTINO%\apps\api\src\evolution\evolution.controller.ts"
copy /Y "%ORIGEM%apps\api\src\evolution\evolution.module.ts" "%DESTINO%\apps\api\src\evolution\evolution.module.ts"
copy /Y "%ORIGEM%apps\api\src\evolution\evolution.types.ts" "%DESTINO%\apps\api\src\evolution\evolution.types.ts"
copy /Y "%ORIGEM%apps\api\src\evolution\evolution-metric.service.ts" "%DESTINO%\apps\api\src\evolution\evolution-metric.service.ts"
if not exist "%DESTINO%\apps\api\src\funnel" mkdir "%DESTINO%\apps\api\src\funnel"
copy /Y "%ORIGEM%apps\api\src\funnel\funnel.controller.ts" "%DESTINO%\apps\api\src\funnel\funnel.controller.ts"
copy /Y "%ORIGEM%apps\api\src\funnel\funnel.module.ts" "%DESTINO%\apps\api\src\funnel\funnel.module.ts"
copy /Y "%ORIGEM%apps\api\src\funnel\funnel.service.ts" "%DESTINO%\apps\api\src\funnel\funnel.service.ts"
if not exist "%DESTINO%\apps\api\src\leo" mkdir "%DESTINO%\apps\api\src\leo"
copy /Y "%ORIGEM%apps\api\src\leo\leo.controller.ts" "%DESTINO%\apps\api\src\leo\leo.controller.ts"
copy /Y "%ORIGEM%apps\api\src\leo\leo.module.ts" "%DESTINO%\apps\api\src\leo\leo.module.ts"
copy /Y "%ORIGEM%apps\api\src\leo\leo.service.ts" "%DESTINO%\apps\api\src\leo\leo.service.ts"
copy /Y "%ORIGEM%apps\api\src\leo\commercial-state.ts" "%DESTINO%\apps\api\src\leo\commercial-state.ts"
rem 19/09: gerador de links UTM + landing (script) + jornada do PWA + testes.
rem ATENCAO: este bat copia a pasta de trabalho POR CIMA do espelho sem checar se o espelho tem commits que a
rem pasta de trabalho nao tem. O commit 617788a ("f", 16/09) apagou a rota /links e o backend do funil exatamente
rem assim. Antes de rodar: confira "git log origin/main" no espelho e compare as arvores. Ver
rem RUNBOOKS\2026-09-19-FUNDACAO-LONGITUDINAL.md secao 9.
copy /Y "%ORIGEM%apps\api\src\links-page.ts" "%DESTINO%\apps\api\src\links-page.ts"
if not exist "%DESTINO%\apps\api\src\landing" mkdir "%DESTINO%\apps\api\src\landing"
copy /Y "%ORIGEM%apps\api\src\landing\script.ts" "%DESTINO%\apps\api\src\landing\script.ts"
copy /Y "%ORIGEM%apps\api\src\landing\data.ts" "%DESTINO%\apps\api\src\landing\data.ts"
copy /Y "%ORIGEM%apps\api\src\landing\styles.ts" "%DESTINO%\apps\api\src\landing\styles.ts"
if not exist "%DESTINO%\apps\mobile\src" mkdir "%DESTINO%\apps\mobile\src"
copy /Y "%ORIGEM%apps\mobile\src\journey.ts" "%DESTINO%\apps\mobile\src\journey.ts"
copy /Y "%ORIGEM%apps\mobile\src\weekWindow.ts" "%DESTINO%\apps\mobile\src\weekWindow.ts"
copy /Y "%ORIGEM%apps\api\test\week-window.spec.ts" "%DESTINO%\apps\api\test\week-window.spec.ts"
copy /Y "%ORIGEM%apps\api\jest.config.ts" "%DESTINO%\apps\api\jest.config.ts"
copy /Y "%ORIGEM%apps\api\test\links-page.spec.ts" "%DESTINO%\apps\api\test\links-page.spec.ts"
copy /Y "%ORIGEM%apps\api\test\funnel.spec.ts" "%DESTINO%\apps\api\test\funnel.spec.ts"
copy /Y "%ORIGEM%apps\api\test\commercial-state.spec.ts" "%DESTINO%\apps\api\test\commercial-state.spec.ts"
copy /Y "%ORIGEM%apps\api\test\journey-foundation.spec.ts" "%DESTINO%\apps\api\test\journey-foundation.spec.ts"
copy /Y "%ORIGEM%apps\api\test\journey-pwa.spec.ts" "%DESTINO%\apps\api\test\journey-pwa.spec.ts"
copy /Y "%ORIGEM%apps\api\test\billing-commercial-history.spec.ts" "%DESTINO%\apps\api\test\billing-commercial-history.spec.ts"
copy /Y "%ORIGEM%apps\api\test\leo-foundation.spec.ts" "%DESTINO%\apps\api\test\leo-foundation.spec.ts"
if not exist "%DESTINO%\apps\api\prisma\migrations\20260919120000_billing_history_baseline_and_payment_unique" mkdir "%DESTINO%\apps\api\prisma\migrations\20260919120000_billing_history_baseline_and_payment_unique"
copy /Y "%ORIGEM%apps\api\prisma\migrations\20260919120000_billing_history_baseline_and_payment_unique\migration.sql" "%DESTINO%\apps\api\prisma\migrations\20260919120000_billing_history_baseline_and_payment_unique\migration.sql"
if not exist "%DESTINO%\RUNBOOKS" mkdir "%DESTINO%\RUNBOOKS"
copy /Y "%ORIGEM%RUNBOOKS\2026-09-19-FUNDACAO-LONGITUDINAL.md" "%DESTINO%\RUNBOOKS\2026-09-19-FUNDACAO-LONGITUDINAL.md"
if not exist "%DESTINO%\apps\api\src\meta" mkdir "%DESTINO%\apps\api\src\meta"
copy /Y "%ORIGEM%apps\api\src\meta\meta-capi.service.ts" "%DESTINO%\apps\api\src\meta\meta-capi.service.ts"
copy /Y "%ORIGEM%apps\mobile\.easignore" "%DESTINO%\apps\mobile\.easignore"
copy /Y "%ORIGEM%apps\mobile\metro.config.js" "%DESTINO%\apps\mobile\metro.config.js"
xcopy /E /I /Y "%ORIGEM%erros persistentes" "%DESTINO%\erros persistentes" 1>nul
echo.
echo Atualizacao copiada para o GitHub Desktop.
echo O GitHub Desktop sera aberto agora.
echo.
start "" "%LOCALAPPDATA%\GitHubDesktop\GitHubDesktop.exe"
timeout /t 3 >nul
