export interface StrengthExercise {
  id: string;
  category: 'Fortalecimento para corredores';
  name: string;
  videoUrl: string;
  description: string;
  focus: string[];
  level: 'base' | 'intermediate' | 'advanced';
  equipment: 'bodyweight' | 'bench' | 'step' | 'box';
}

export const runnerStrengthCategory = 'Fortalecimento para corredores';

export const runnerStrengthExercises: StrengthExercise[] = [
  {
    id: 'salto-lateral-troca-base',
    category: runnerStrengthCategory,
    name: 'Salto lateral com troca de base',
    videoUrl: 'https://youtu.be/dP1hNWUQYpk',
    description: 'Salto lateral alternando apoio e posicao dos pes.',
    focus: ['pliometria', 'coordenacao', 'estabilidade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'skip-123',
    category: runnerStrengthCategory,
    name: 'Skip 1,2,3',
    videoUrl: 'https://youtu.be/Em63-6BzgKI',
    description: 'Coordenacao de corrida com elevacao alternada dos joelhos.',
    focus: ['tecnica', 'coordenacao'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'levantar-unilateral-salto-lateral',
    category: runnerStrengthCategory,
    name: 'Levantar unilateral com salto lateral',
    videoUrl: 'https://youtu.be/ddvjckGeUc0',
    description: 'Levantar em uma perna e saltar lateralmente com controle.',
    focus: ['forca unilateral', 'potencia', 'estabilidade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'agachamento-unilateral-isometrico-salto',
    category: runnerStrengthCategory,
    name: 'Agachamento unilateral isometrico com salto',
    videoUrl: 'https://youtu.be/MaNB9VtAbUg',
    description: 'Sustentacao unilateral seguida de salto curto.',
    focus: ['forca unilateral', 'isometria', 'potencia'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'sapinho',
    category: runnerStrengthCategory,
    name: 'Sapinho',
    videoUrl: 'https://youtu.be/t_Q10chbArA',
    description: 'Salto curto em posicao baixa, trabalhando potencia de pernas.',
    focus: ['potencia', 'quadriceps', 'gluteos'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'lunge',
    category: runnerStrengthCategory,
    name: 'Lunge',
    videoUrl: 'https://youtu.be/kEkObS9dUT8',
    description: 'Avanco alternado para forca de quadriceps e gluteos.',
    focus: ['quadriceps', 'gluteos', 'estabilidade'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'flexao-quadril-ajoelhado',
    category: runnerStrengthCategory,
    name: 'Flexao quadril ajoelhado',
    videoUrl: 'https://youtu.be/aQNWWecGElc',
    description: 'Mobilidade e ativacao de flexores do quadril.',
    focus: ['mobilidade', 'quadril'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'abdominal-mao-no-pe',
    category: runnerStrengthCategory,
    name: 'Abdominal mao no pe',
    videoUrl: 'https://youtu.be/L3FnilwSiLM',
    description: 'Abdominal dinamico aproximando maos e pes.',
    focus: ['core'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'balancinho',
    category: runnerStrengthCategory,
    name: 'Balancinho',
    videoUrl: 'https://youtu.be/DeswUt-qQZA',
    description: 'Movimento de balanco para controle corporal e core.',
    focus: ['core', 'controle corporal'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'mountain-climber',
    category: runnerStrengthCategory,
    name: 'Mountain climber',
    videoUrl: 'https://youtu.be/C8fdbCJ5PXM',
    description: 'Prancha dinamica alternando joelhos a frente.',
    focus: ['core', 'condicionamento'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'prancha-mao-no-ombro',
    category: runnerStrengthCategory,
    name: 'Prancha mao no ombro',
    videoUrl: 'https://youtu.be/IkPdOsqG3Ec',
    description: 'Prancha tocando ombros alternadamente, com estabilidade.',
    focus: ['core', 'estabilidade'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'prancha-abre-fecha',
    category: runnerStrengthCategory,
    name: 'Prancha abre e fecha',
    videoUrl: 'https://youtu.be/yAImp7GIxbE',
    description: 'Prancha com abertura e fechamento dos pes.',
    focus: ['core', 'estabilidade'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'elevacao-pelvica-alternada',
    category: runnerStrengthCategory,
    name: 'Elevacao pelvica alternada',
    videoUrl: 'https://youtu.be/EowhdROF388',
    description: 'Ponte de gluteo alternando apoio das pernas.',
    focus: ['gluteos', 'posterior'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'tibial-anterior-unilateral',
    category: runnerStrengthCategory,
    name: 'Tibial anterior unilateral',
    videoUrl: 'https://youtu.be/1oBLee78bwE',
    description: 'Fortalecimento do tibial anterior em uma perna.',
    focus: ['tibial anterior', 'tornozelo'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'tibial-anterior',
    category: runnerStrengthCategory,
    name: 'Tibial anterior',
    videoUrl: 'https://youtu.be/jSgy_-ZKDmc',
    description: 'Fortalecimento do tibial anterior bilateral.',
    focus: ['tibial anterior', 'tornozelo'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'elevacao-pelvica-unilateral',
    category: runnerStrengthCategory,
    name: 'Elevacao Pelvica Unilateral',
    videoUrl: 'https://youtu.be/2sYzzf_1iLA',
    description: 'Ponte de gluteo com uma perna elevada.',
    focus: ['gluteos', 'posterior', 'forca unilateral'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'elevacao-pelvica',
    category: runnerStrengthCategory,
    name: 'Elevacao pelvica',
    videoUrl: 'https://youtu.be/9h62LKgG94g',
    description: 'Ponte de gluteo bilateral para cadeia posterior.',
    focus: ['gluteos', 'posterior'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'prancha-lateral',
    category: runnerStrengthCategory,
    name: 'Prancha Lateral',
    videoUrl: 'https://youtu.be/-WdRN4l3zeM',
    description: 'Isometria lateral para core e estabilidade.',
    focus: ['core', 'estabilidade'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'reativo-despencando-salto',
    category: runnerStrengthCategory,
    name: 'Reativo despencando + salto',
    videoUrl: 'https://youtu.be/27437VhvG-k',
    description: 'Queda controlada seguida de salto reativo.',
    focus: ['pliometria', 'reatividade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'reativo-despencando',
    category: runnerStrengthCategory,
    name: 'Reativo Despencando',
    videoUrl: 'https://youtu.be/gW6PfzVaE6Y',
    description: 'Queda controlada para treino de reacao e aterrissagem.',
    focus: ['reatividade', 'aterrissagem'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha-unilateral-saltitos',
    category: runnerStrengthCategory,
    name: 'Panturrilha Unilateral com saltitos',
    videoUrl: 'https://youtu.be/wvkQPLXvZuk',
    description: 'Saltitos em uma perna para panturrilha e elasticidade.',
    focus: ['panturrilha', 'elasticidade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha-saltitos',
    category: runnerStrengthCategory,
    name: 'Panturrilha com saltitos',
    videoUrl: 'https://youtu.be/4Gy4paBQHFc',
    description: 'Saltitos bilaterais para panturrilha e reatividade.',
    focus: ['panturrilha', 'reatividade'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha-unilateral',
    category: runnerStrengthCategory,
    name: 'Panturrilha unilateral',
    videoUrl: 'https://youtu.be/rmz5_eAdm90',
    description: 'Elevacao de panturrilha com uma perna.',
    focus: ['panturrilha', 'forca unilateral'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha',
    category: runnerStrengthCategory,
    name: 'Panturrilha',
    videoUrl: 'https://youtu.be/t79kBan0iko',
    description: 'Elevacao de panturrilha bilateral.',
    focus: ['panturrilha'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'aviao-subir-degrau',
    category: runnerStrengthCategory,
    name: 'Aviaozinho + subir no degrau',
    videoUrl: 'https://youtu.be/elX9_YQyYXc',
    description: 'Equilibrio unilateral seguido de subida no degrau.',
    focus: ['equilibrio', 'gluteos', 'forca unilateral'],
    level: 'intermediate',
    equipment: 'step',
  },
  {
    id: 'aviao-rodando-quadril',
    category: runnerStrengthCategory,
    name: 'Aviaozinho rodando o quadril',
    videoUrl: 'https://youtu.be/qk8JmNEz3lA',
    description: 'Equilibrio unilateral com rotacao controlada do quadril.',
    focus: ['equilibrio', 'quadril'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'aviao-123',
    category: runnerStrengthCategory,
    name: 'Aviaozinho 1,2,3',
    videoUrl: 'https://youtu.be/lJSNVN9Y2UA',
    description: 'Variacao progressiva de equilibrio em uma perna.',
    focus: ['equilibrio', 'estabilidade'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'aviao',
    category: runnerStrengthCategory,
    name: 'Aviaozinho',
    videoUrl: 'https://youtu.be/DYSBwE6LFv4',
    description: 'Equilibrio unilateral com inclinacao do tronco.',
    focus: ['equilibrio', 'posterior'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'levantar-subindo-banco',
    category: runnerStrengthCategory,
    name: 'Levantar subindo banco',
    videoUrl: 'https://youtu.be/5LK2hHzWgto',
    description: 'Levantar e subir no banco com controle.',
    focus: ['quadriceps', 'gluteos'],
    level: 'intermediate',
    equipment: 'bench',
  },
  {
    id: 'skip-chao-step',
    category: runnerStrengthCategory,
    name: 'Skip levantando do chao com step',
    videoUrl: 'https://youtu.be/ShVV61fSH0Y',
    description: 'Saida do chao com skip usando step.',
    focus: ['tecnica', 'coordenacao'],
    level: 'intermediate',
    equipment: 'step',
  },
  {
    id: 'skip-chao',
    category: runnerStrengthCategory,
    name: 'Skip levantando do chao',
    videoUrl: 'https://youtu.be/RjrANf8qcEk',
    description: 'Saida do chao com movimento de skip.',
    focus: ['tecnica', 'coordenacao'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'passar-cima-caixa',
    category: runnerStrengthCategory,
    name: 'Passar por cima da caixa',
    videoUrl: 'https://youtu.be/H5KdEUTlGiA',
    description: 'Deslocamento passando sobre caixa ou obstaculo.',
    focus: ['mobilidade', 'coordenacao'],
    level: 'base',
    equipment: 'box',
  },
  {
    id: 'step-up-lateral',
    category: runnerStrengthCategory,
    name: 'Step up lateral',
    videoUrl: 'https://youtu.be/W9hHUKNzAno',
    description: 'Subida lateral no step para forca e controle.',
    focus: ['gluteos', 'estabilidade'],
    level: 'base',
    equipment: 'step',
  },
  {
    id: 'step-up',
    category: runnerStrengthCategory,
    name: 'Step up',
    videoUrl: 'https://youtu.be/LqPt6hk4wEc',
    description: 'Subida frontal no step para membros inferiores.',
    focus: ['quadriceps', 'gluteos'],
    level: 'base',
    equipment: 'step',
  },
  {
    id: 'bulgaro-saltos',
    category: runnerStrengthCategory,
    name: 'Bulgaro com saltos',
    videoUrl: 'https://youtu.be/Os4QRKruZSk',
    description: 'Agachamento bulgaro com salto.',
    focus: ['potencia', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'bulgaro-saltitos',
    category: runnerStrengthCategory,
    name: 'Bulgaro com saltitos',
    videoUrl: 'https://youtu.be/bmQeWstkWUs',
    description: 'Agachamento bulgaro com pequenos saltos.',
    focus: ['reatividade', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'bulgaro-despencando',
    category: runnerStrengthCategory,
    name: 'Bulgaro despencando',
    videoUrl: 'https://youtu.be/cittDSPxVr4',
    description: 'Bulgaro com queda controlada e reacao.',
    focus: ['reatividade', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'bulgaro',
    category: runnerStrengthCategory,
    name: 'Bulgaro',
    videoUrl: 'https://youtu.be/7Gu1llqiH0I',
    description: 'Agachamento bulgaro tradicional.',
    focus: ['quadriceps', 'gluteos', 'forca unilateral'],
    level: 'base',
    equipment: 'bench',
  },
  {
    id: 'bulgaro-isometrico-braco',
    category: runnerStrengthCategory,
    name: 'Bulgaro isometrico rodando o braco',
    videoUrl: 'https://youtu.be/1SMX1GL62wQ',
    description: 'Isometria no bulgaro com rotacao dos bracos.',
    focus: ['isometria', 'estabilidade'],
    level: 'intermediate',
    equipment: 'bench',
  },
  {
    id: 'levantar-banco-unilateral',
    category: runnerStrengthCategory,
    name: 'Levantar do Banco Unilateral',
    videoUrl: 'https://youtu.be/NZ9HyUMSN3g',
    description: 'Levantar do banco usando uma perna.',
    focus: ['forca unilateral', 'quadriceps', 'gluteos'],
    level: 'base',
    equipment: 'bench',
  },
  {
    id: 'levantar-saltando-banco',
    category: runnerStrengthCategory,
    name: 'Levantar saltando do banco',
    videoUrl: 'https://youtu.be/zigTLmgQIIU',
    description: 'Levantar do banco com salto ao final.',
    focus: ['potencia', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
];

export function selectRunnerStrengthExercises(durationMin: number) {
  const exerciseCount = durationMin >= 60 ? 6 : durationMin >= 45 ? 5 : 4;
  const baseOrder = [
    'lunge',
    'step-up',
    'elevacao-pelvica',
    'panturrilha',
    'prancha-lateral',
    'tibial-anterior',
  ];

  return baseOrder
    .map((id) => runnerStrengthExercises.find((exercise) => exercise.id === id))
    .filter((exercise): exercise is StrengthExercise => Boolean(exercise))
    .slice(0, exerciseCount);
}
