export interface StrengthExercise {
  id: string;
  category: 'Fortalecimento para corredores';
  name: string;
  videoUrl: string;
  description: string;
  focus: string[];
  level: 'base' | 'intermediate' | 'advanced';
  equipment: 'bodyweight' | 'bench' | 'step' | 'box';
}

export const runnerStrengthCategory = 'Fortalecimento para corredores';

export const runnerStrengthExercises: StrengthExercise[] = [
  {
    id: 'salto-lateral-troca-base',
    category: runnerStrengthCategory,
    name: 'Salto lateral com troca de base',
    videoUrl: 'https://youtu.be/dP1hNWUQYpk',
    description: 'Exercicio importante para melhorar o tempo de contato com o solo, melhorando o ciclo alongamento encurtamento. Exige bastante de musculos e tendoes da panturrilha. Gluteos e quadriceps sao bem recrutados para estabilizar o movimento. Importante para a coordenacao motora.',
    focus: ['pliometria', 'coordenacao', 'estabilidade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'skip-123',
    category: runnerStrengthCategory,
    name: 'Skip 1,2,3',
    videoUrl: 'https://youtu.be/Em63-6BzgKI',
    description: 'Exercicio excelente para corredores. Ele e importante para manter o stiffness, que seria a rigidez tendinea. Importante para melhorar a forca especialmente do tendao de Aquiles. Para corredores que fazem uma corrida pesada, carregada, sem aproveitar a energia do impacto de cada passada. Esse exercicio e excelente para coordenacao motora de corredores e para melhorar a performance, especialmente ao final das provas, quando a fadiga se acumula e a eficiencia mecanica fica comprometida.',
    focus: ['tecnica', 'coordenacao'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'levantar-unilateral-salto-lateral',
    category: runnerStrengthCategory,
    name: 'Levantar unilateral com salto lateral',
    videoUrl: 'https://youtu.be/ddvjckGeUc0',
    description: 'Exercicio para correr melhor. Exige forca de gluteos e posterior da coxa. Quadriceps tambem precisa fazer bastante forca. Forte componente concentrico. Melhora coordenacao motora. Ajuda na eficiencia mecanica da corrida. Otimo para prevencao de lesoes em corredores.',
    focus: ['forca unilateral', 'potencia', 'estabilidade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'agachamento-unilateral-isometrico-salto',
    category: runnerStrengthCategory,
    name: 'Agachamento unilateral isometrico com salto',
    videoUrl: 'https://youtu.be/MaNB9VtAbUg',
    description: 'Exercicio de forca para correr melhor. Excelente para melhorar a fadiga durante a corrida. Otimo para treinar musculos estabilizadores da postura durante a corrida.',
    focus: ['forca unilateral', 'isometria', 'potencia'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'sapinho',
    category: runnerStrengthCategory,
    name: 'Sapinho',
    videoUrl: 'https://youtu.be/t_Q10chbArA',
    description: 'Excelente exercicio para melhorar a forca das pernas. Ajuda na corrida melhorando a forca da panturrilha e quadriceps. Muito importante para ajudar na eficiencia mecanica da corrida.',
    focus: ['potencia', 'quadriceps', 'gluteos'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'lunge',
    category: runnerStrengthCategory,
    name: 'Lunge',
    videoUrl: 'https://youtu.be/kEkObS9dUT8',
    description: 'Excelente exercicio para gluteo. Otima opcao para corredores que precisam melhorar forca do quadril, inclusive para ajudar na estabilizacao dos joelhos durante a corrida. Grande demanda de forca, ajudando muito a cansar menos durante a corrida.',
    focus: ['quadriceps', 'gluteos', 'estabilidade'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'flexao-quadril-ajoelhado',
    category: runnerStrengthCategory,
    name: 'Flexao quadril ajoelhado',
    videoUrl: 'https://youtu.be/aQNWWecGElc',
    description: 'Excelente exercicio para melhorar forca do quadriceps. Importante ressaltar que pessoas com dores no joelho podem fazer, mas pelo grau de dificuldade devem comecar com a execucao mais facil e depois ir dificultando. Ajuda muito a melhorar o fortalecimento de joelhos.',
    focus: ['mobilidade', 'quadril'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'abdominal-mao-no-pe',
    category: runnerStrengthCategory,
    name: 'Abdominal mao no pe',
    videoUrl: 'https://youtu.be/L3FnilwSiLM',
    description: 'Excelente exercicio para abdomen e importante para ajudar na estabilidade durante a corrida, ajudando principalmente corredores no final de provas longas ou corredores iniciantes.',
    focus: ['core'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'balancinho',
    category: runnerStrengthCategory,
    name: 'Balancinho',
    videoUrl: 'https://youtu.be/DeswUt-qQZA',
    description: 'Excelente exercicio para abdomen e importante para ajudar na estabilidade durante a corrida, ajudando principalmente corredores no final de provas longas. Exercicio mais dificil para quem e iniciante ou tem dores na lombar.',
    focus: ['core', 'controle corporal'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'mountain-climber',
    category: runnerStrengthCategory,
    name: 'Mountain climber',
    videoUrl: 'https://youtu.be/C8fdbCJ5PXM',
    description: 'Excelente exercicio para corredores que precisam melhorar forca de flexores de quadril. Excelente para ajudar na estabilidade durante a corrida. Importante para ter mais forca abdominal.',
    focus: ['core', 'condicionamento'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'prancha-mao-no-ombro',
    category: runnerStrengthCategory,
    name: 'Prancha mao no ombro',
    videoUrl: 'https://youtu.be/IkPdOsqG3Ec',
    description: 'Excelente exercicio para quem deseja melhorar fortalecimento de core. Bom exercicio de fortalecimento para corredores que costumam cansar muito durante a segunda metade da prova. Ajuda a manter a postura ate o final da prova. Bom tambem para iniciantes na corrida correrem com mais firmeza e estabilidade.',
    focus: ['core', 'estabilidade'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'prancha-abre-fecha',
    category: runnerStrengthCategory,
    name: 'Prancha abre e fecha',
    videoUrl: 'https://youtu.be/yAImp7GIxbE',
    description: 'Para correr com mais estabilidade do tronco, protegendo mais as costas e quadril durante a corrida. Ajuda a nao perder a tecnica de corrida durante as provas mais longas e ajuda os corredores iniciantes a correrem com mais estabilidade do corpo.',
    focus: ['core', 'estabilidade'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'elevacao-pelvica-alternada',
    category: runnerStrengthCategory,
    name: 'Elevacao pelvica alternada',
    videoUrl: 'https://youtu.be/EowhdROF388',
    description: 'Para melhorar a corrida e importante melhorar a forca de posteriores de coxa e de gluteo. Esse exercicio ajuda muito na prevencao de lesoes no posterior de coxa, especialmente nos treinos de corrida mais intensa. Para quem deseja correr com seguranca, esse exercicio ajuda tambem na regulacao da diferenca de forca entre posteriores e quadriceps, protegendo o joelho, especialmente de quem corre ou mesmo joga futebol. Ele gera bastante potencia dos musculos envolvidos. Tambem melhora a coordenacao motora do atleta.',
    focus: ['gluteos', 'posterior'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'tibial-anterior-unilateral',
    category: runnerStrengthCategory,
    name: 'Tibial anterior unilateral',
    videoUrl: 'https://youtu.be/1oBLee78bwE',
    description: 'Corredores precisam fortalecer musculos envolvidos com os movimentos dos pes. Esse exercicio de fortalecimento para corredores, voltado para regiao tibial, ajuda a evitar e tratar a canelite. Ajuda a preparar o corpo para absorver bem os impactos da corrida e usa-lo para gerar mais propulsao em cada passada.',
    focus: ['tibial anterior', 'tornozelo'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'tibial-anterior',
    category: runnerStrengthCategory,
    name: 'Tibial anterior',
    videoUrl: 'https://youtu.be/jSgy_-ZKDmc',
    description: 'Importante exercicio para corredores que sofrem com canelite. Ajuda muito na prevencao de dores para corredores. Importante para fortalecer os musculos das pernas para ajudar na utilizacao do impacto da corrida, para melhorar a tecnica de corrida.',
    focus: ['tibial anterior', 'tornozelo'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'elevacao-pelvica-unilateral',
    category: runnerStrengthCategory,
    name: 'Elevacao Pelvica Unilateral',
    videoUrl: 'https://youtu.be/2sYzzf_1iLA',
    description: 'Os musculos do gluteo e posterior da coxa sao fundamentais para corredores. Nas corridas com velocidades maiores os posteriores da coxa sao muito recrutados ao mesmo tempo que estao alongados e isso gera maior risco de estiramento. Jogadores de futebol sofrem muito com esse tipo de lesao, principalmente nos sprints e arrancadas. Esse exercicio ajuda na estabilidade do quadril, garantindo melhor eficiencia mecanica e inclusive tambem ajudando a preservar o joelho do corredor.',
    focus: ['gluteos', 'posterior', 'forca unilateral'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'elevacao-pelvica',
    category: runnerStrengthCategory,
    name: 'Elevacao pelvica',
    videoUrl: 'https://youtu.be/9h62LKgG94g',
    description: 'Os posteriores da coxa sao muito exigidos nas corridas, especialmente nos sprints e corridas com velocidades maiores. Os musculos do quadril, em especial o gluteo, tambem ajudam muito na fase de absorcao do impacto e na fase de propulsao. Treinar esses musculos com a elevacao pelvica no chao e uma excelente oportunidade de melhorar a qualidade e seguranca do corredor.',
    focus: ['gluteos', 'posterior'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'prancha-lateral',
    category: runnerStrengthCategory,
    name: 'Prancha Lateral',
    videoUrl: 'https://youtu.be/-WdRN4l3zeM',
    description: 'Exercicios de prancha sao usualmente utilizados para melhorar a forca abdominal. A prancha lateral e um excelente exercicio entre esses, mas tambem ajuda muito na forca de gluteo medio e outros estabilizadores do quadril. Inclusive e uma excelente opcao para quem corre e tem dores nos joelhos. Ele ajuda muito a evitar o famoso tilt pelvico. Sendo peca importante para um bom programa de prevencao e tratamento de dores tanto em joelhos quanto quadris.',
    focus: ['core', 'estabilidade'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'reativo-despencando-salto',
    category: runnerStrengthCategory,
    name: 'Reativo despencando + salto',
    videoUrl: 'https://youtu.be/27437VhvG-k',
    description: 'O ciclo alongamento encurtamento basicamente e aproveitar a energia da fase excentrica para ajudar na fase concentrica. Esse mecanismo e fundamental para correr com mais seguranca, prevenindo lesoes e fortalecendo tambem tendoes. Quem corre pode fazer esse exercicio que tem uma otima fase de frenagem do movimento para posterior reutilizacao dessa energia para gerar contracao muscular para realizar o salto seguinte. Corredores que possuem uma boa capacidade de saltar, especialmente com um contramovimento anterior, possuem mais protecao para sua corrida.',
    focus: ['pliometria', 'reatividade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'reativo-despencando',
    category: runnerStrengthCategory,
    name: 'Reativo Despencando',
    videoUrl: 'https://youtu.be/gW6PfzVaE6Y',
    description: 'Excelente para melhorar a tecnica de corrida, pois treina o ciclo alongamento encurtamento do corredor. Alem de treinar os musculos das pernas, treina tambem os tendoes para gerarem forca. Dessa forma, esse exercicio pode ser feito por corredores que precisam melhorar a capacidade de correr mais rapido ou distancias maiores. Sendo protetivo contra lesoes e ainda ajudando na performance.',
    focus: ['reatividade', 'aterrissagem'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha-unilateral-saltitos',
    category: runnerStrengthCategory,
    name: 'Panturrilha Unilateral com saltitos',
    videoUrl: 'https://youtu.be/wvkQPLXvZuk',
    description: 'A panturrilha e um dos principais musculos da corrida e o tendao de Aquiles fornece grande energia para absorver e utilizar o impacto em cada passada. Usar esse exercicio vai tornar a corrida mais eficiente e ajudar a economizar energia, especialmente para corredores iniciantes e que ainda estao com mais peso, pois esse exercicio vai tornar os tendoes mais fortes e ajudar tambem na prevencao de lesoes.',
    focus: ['panturrilha', 'elasticidade'],
    level: 'advanced',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha-saltitos',
    category: runnerStrengthCategory,
    name: 'Panturrilha com saltitos',
    videoUrl: 'https://youtu.be/4Gy4paBQHFc',
    description: 'Treinar a capacidade dos tendoes de gerar forca e tao importante quanto treinar os musculos. Esse exercicio vai ajudar corredores iniciantes e avancados a gerar a rigidez tendinea, importante fator de protecao e performance esportiva. Durante a corrida, longa e/ou intensa, o corredor perde a capacidade de aplicar forca. Isso faz o corredor gastar mais energia para um mesmo ritmo. Esse e um dos motivos pelo qual muitos corredores quebram na segunda parte da corrida. Esse exercicio e portanto um aliado no controle da fadiga.',
    focus: ['panturrilha', 'reatividade'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha-unilateral',
    category: runnerStrengthCategory,
    name: 'Panturrilha unilateral',
    videoUrl: 'https://youtu.be/rmz5_eAdm90',
    description: 'A panturrilha e conhecida pelo seu importante papel na corrida. Treinar esse musculo e os tendoes relacionados com o tornozelo, faz todo sentido para o corredor que precisa sustentar maiores velocidades e distancias. Importante exercicio para quem deseja correr e ainda esta com sobrepeso.',
    focus: ['panturrilha', 'forca unilateral'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'panturrilha',
    category: runnerStrengthCategory,
    name: 'Panturrilha',
    videoUrl: 'https://youtu.be/t79kBan0iko',
    description: 'Esse e um tradicional e importante exercicio para corredores melhorarem sua corrida, em especial os iniciantes. Treinar a panturrilha ajuda na prevencao de dores e lesoes e melhora a estabilidade durante a corrida.',
    focus: ['panturrilha'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'aviao-subir-degrau',
    category: runnerStrengthCategory,
    name: 'Aviaozinho + subir no degrau',
    videoUrl: 'https://youtu.be/elX9_YQyYXc',
    description: 'Esse e um exercicio que envolve todo o corpo e por isso ajuda a treinar muitos musculos. Seu principal papel e ensinar aos musculos a trabalharem de forma sincronizada, harmoniosa e equilibrada. Portanto ele pode ser usado com objetivo de melhorar a eficiencia mecanica, bem como melhorar a qualidade de musculos dos pes, joelhos e quadril. Excelente opcao para iniciantes e avancados.',
    focus: ['equilibrio', 'gluteos', 'forca unilateral'],
    level: 'intermediate',
    equipment: 'step',
  },
  {
    id: 'aviao-rodando-quadril',
    category: runnerStrengthCategory,
    name: 'Aviaozinho rodando o quadril',
    videoUrl: 'https://youtu.be/qk8JmNEz3lA',
    description: 'Alem de ajudar os musculos do corredor a trabalharem em equipe de forma harmoniosa, esse exercicio ajuda muito a cuidar de quem corre e sente dores no quadril. Sendo assim, importante para tratamento e prevencao de dores para quem corre e sente dores no quadril.',
    focus: ['equilibrio', 'quadril'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'aviao-123',
    category: runnerStrengthCategory,
    name: 'Aviaozinho 1,2,3',
    videoUrl: 'https://youtu.be/lJSNVN9Y2UA',
    description: 'Alem de ajudar na postura, esse exercicio ajuda na melhora da tecnica de corrida. Ajuda a treinar a estabilidade de quadril e tronco, bem como ajuda a treinar a producao de forca de panturrilha e flexores de quadril. Especialmente a medida que a fadiga se acumula, o corredor tende a correr com o corpo mais frouxo. Isso reduz a rigidez tendinea, o que pode aumentar o risco de lesoes e perda de desempenho. Esse e um dos melhores exercicios para quem deseja sustentar a postura ate a linha de chegada.',
    focus: ['equilibrio', 'estabilidade'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'aviao',
    category: runnerStrengthCategory,
    name: 'Aviaozinho',
    videoUrl: 'https://youtu.be/DYSBwE6LFv4',
    description: 'Um dos melhores exercicios para corredores que precisam melhorar a forca e a estabilidade do corpo durante a corrida. Especialmente iniciantes que sentem dores, quanto corredores avancados que precisam sustentar o desempenho ate o final das provas. Por isso e excelente para treinar quem deseja prevenir lesoes em joelhos, quadril e ate mesmo a canelite.',
    focus: ['equilibrio', 'posterior'],
    level: 'base',
    equipment: 'bodyweight',
  },
  {
    id: 'levantar-subindo-banco',
    category: runnerStrengthCategory,
    name: 'Levantar subindo banco',
    videoUrl: 'https://youtu.be/5LK2hHzWgto',
    description: 'Esse exercicio exige muito dos membros inferiores, tanto posteriores de coxa, gluteo, quanto quadriceps. Ele tambem ajuda na estabilidade de tronco, joelho e quadril e portanto pode ser usado para o corredor que deseja melhorar a capacidade do corpo de se movimentar com harmonia, estabilidade e eficiencia.',
    focus: ['quadriceps', 'gluteos'],
    level: 'intermediate',
    equipment: 'bench',
  },
  {
    id: 'skip-chao-step',
    category: runnerStrengthCategory,
    name: 'Skip levantando do chao com step',
    videoUrl: 'https://youtu.be/ShVV61fSH0Y',
    description: 'Um excelente exercicio para treinar posterior de coxas, gluteo e quadriceps. Especialmente pois exige sincronia do movimento, treinando os musculos a trabalharem de forma harmoniosa. Uma otima opcao para quem deseja correr rapido.',
    focus: ['tecnica', 'coordenacao'],
    level: 'intermediate',
    equipment: 'step',
  },
  {
    id: 'skip-chao',
    category: runnerStrengthCategory,
    name: 'Skip levantando do chao',
    videoUrl: 'https://youtu.be/RjrANf8qcEk',
    description: 'Exercicio excelente especialmente para corredores que ainda nao conseguem correr rapido, pois esse exercicio melhora muito a forca de membros inferiores.',
    focus: ['tecnica', 'coordenacao'],
    level: 'intermediate',
    equipment: 'bodyweight',
  },
  {
    id: 'passar-cima-caixa',
    category: runnerStrengthCategory,
    name: 'Passar por cima da caixa',
    videoUrl: 'https://youtu.be/H5KdEUTlGiA',
    description: 'Esse exercicio treina muito a forca de membros inferiores para quem deseja correr com mais seguranca e estabilidade, prevenindo assim dores, lesoes e a queda da performance especialmente na segunda metade das provas.',
    focus: ['mobilidade', 'coordenacao'],
    level: 'base',
    equipment: 'box',
  },
  {
    id: 'step-up-lateral',
    category: runnerStrengthCategory,
    name: 'Step up lateral',
    videoUrl: 'https://youtu.be/W9hHUKNzAno',
    description: 'Esse e um dos exercicios que mais ativam o gluteo maximo. Mas ele e importante nao so para esse musculo, mas para todo o sistema locomotor de quem pratica corrida. Ajudando a aumentar a forca e assim prevenindo dores, lesoes e ajudando no desempenho. O corredor vai correr mais rapido sem gastar tanta energia. O que chamamos de eficiencia mecanica.',
    focus: ['gluteos', 'estabilidade'],
    level: 'base',
    equipment: 'step',
  },
  {
    id: 'step-up',
    category: runnerStrengthCategory,
    name: 'Step up',
    videoUrl: 'https://youtu.be/LqPt6hk4wEc',
    description: 'O exercicio que mais ativa o gluteo, mas importante tambem para corredores que desejam estabilidade do quadril e forca de membros inferiores.',
    focus: ['quadriceps', 'gluteos'],
    level: 'base',
    equipment: 'step',
  },
  {
    id: 'bulgaro-saltos',
    category: runnerStrengthCategory,
    name: 'Bulgaro com saltos',
    videoUrl: 'https://youtu.be/Os4QRKruZSk',
    description: 'Esse e um exercicio que exige muita forca e por isso e importante para o corredor que deseja melhorar sua forca para correr economizando energia e ainda garantindo maior seguranca e qualidade da propria corrida. Treinar esse exercicio tambem vai ajudar quem deseja correr com mais velocidade e ainda assim conseguir sustentar a performance.',
    focus: ['potencia', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'bulgaro-saltitos',
    category: runnerStrengthCategory,
    name: 'Bulgaro com saltitos',
    videoUrl: 'https://youtu.be/bmQeWstkWUs',
    description: 'Importante exercicio para corredores que desejam melhorar a capacidade de forca das pernas para garantirem melhor performance na corrida. Correndo gastando menos energia e ate mesmo conseguindo correr mais forte.',
    focus: ['reatividade', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'bulgaro-despencando',
    category: runnerStrengthCategory,
    name: 'Bulgaro despencando',
    videoUrl: 'https://youtu.be/cittDSPxVr4',
    description: 'Esse exercicio e importante para treinar musculos e tendoes envolvidos na corrida. Excelente especialmente para corredores que sentem dores e estiramento quando fazem corridas mais fortes. Ele ajuda tanto na estabilidade do corpo durante a corrida, como na capacidade de usar a energia do impacto para conseguir correr mais forte sem cansar tanto. Sendo excelente para prevencao de dores e lesoes e otimo para economizar energia na corrida.',
    focus: ['reatividade', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'bulgaro',
    category: runnerStrengthCategory,
    name: 'Bulgaro',
    videoUrl: 'https://youtu.be/7Gu1llqiH0I',
    description: 'Tradicional exercicio para membros inferiores, em especial o gluteo. Por isso ele ajuda corredores a cuidarem da prevencao e tratamento de dores e lesoes nas articulacoes dos joelhos e quadris.',
    focus: ['quadriceps', 'gluteos', 'forca unilateral'],
    level: 'base',
    equipment: 'bench',
  },
  {
    id: 'bulgaro-isometrico-braco',
    category: runnerStrengthCategory,
    name: 'Bulgaro isometrico rodando o braco',
    videoUrl: 'https://youtu.be/1SMX1GL62wQ',
    description: 'Especialmente para quem sente dores e esta com tendinopatias em regioes que envolvem tornozelo, joelho e quadril, esse e um potente exercicio para iniciar o tratamento e prevencao de dores. Quem corre precisa cuidar bem das articulacoes e realizar exercicios de forca como esse.',
    focus: ['isometria', 'estabilidade'],
    level: 'intermediate',
    equipment: 'bench',
  },
  {
    id: 'levantar-banco-unilateral',
    category: runnerStrengthCategory,
    name: 'Levantar do Banco Unilateral',
    videoUrl: 'https://youtu.be/NZ9HyUMSN3g',
    description: 'Um dos melhores exercicios para treinar forca dos musculos inferiores e ainda treinar estabilidade ao mesmo tempo. Com o banco mais alto e excelente para treinar forca com idosos, a medida que o banco fica mais baixo a dificuldade aumenta e ate mesmo corredores de elite podem se aproveitar desse exercicio para melhorar a performance. Ele exige muita estabilidade o que e excelente para quem tem dores nas articulacoes de tornozelo, joelho e quadril.',
    focus: ['forca unilateral', 'quadriceps', 'gluteos'],
    level: 'base',
    equipment: 'bench',
  },
  {
    id: 'levantar-saltando-banco',
    category: runnerStrengthCategory,
    name: 'Levantar saltando do banco',
    videoUrl: 'https://youtu.be/zigTLmgQIIU',
    description: 'Excelente forma de treinar a fase concentrica da forca de pernas. Isso ajuda corredores a terem mais forca durante a corrida, garantindo mais eficiencia mecanica. Corre mais, poupando energia e portanto cansando menos.',
    focus: ['potencia', 'forca unilateral'],
    level: 'advanced',
    equipment: 'bench',
  },
  {
    id: 'saltito-abre-fecha-step',
    category: runnerStrengthCategory,
    name: 'Saltito abre e fecha no step',
    videoUrl: 'https://youtu.be/LDHm6bm5KTw',
    description: 'Excelente para corredores. Treinar tempo de contato com solo. Treinar ciclo alongamento encurtamento. Excelente para panturrilha. Excelente para coordenacao motora.',
    focus: ['panturrilha', 'coordenacao'],
    level: 'intermediate',
    equipment: 'step',
  },
  {
    id: 'subir-step-1234',
    category: runnerStrengthCategory,
    name: 'Subir no step 1,2,3,4',
    videoUrl: 'https://youtu.be/Wtq_ocv6aV8',
    description: 'Objetivo treinar tempo de contato com solo. Excelente para corredores. Excelente para treinar panturrilha e coordenacao motora.',
    focus: ['panturrilha', 'coordenacao'],
    level: 'base',
    equipment: 'step',
  },
];
